name: PQClean Comprehensive Testing

on: 
  [push, pull_request]

concurrency:
  group: ci-common-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, i386]
        cc: [gcc, clang]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      # Step 2: Set up dependencies
      - name: Set up Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc make time python3 python3-pip

      # Step 3: Cache dependencies
      - name: Cache Ccache
        uses: actions/cache@v3
        with:
          path: /ccache
          key: cache-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.arch }}

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}

      # Step 4: Run tests
      - name: Run Benchmark Tests
        run: |
          cd crypto_sign/falcon-512/clean
          gcc -o benchmark_time time_benchmark.c
          ./benchmark_time > time_benchmark_results.txt
          gcc -o benchmark_cost cost_benchmark.c
          /usr/bin/time -v ./benchmark_cost > cost_benchmark_results.txt
          gcc -o benchmark_throughput throughput_benchmark.c
          ./benchmark_throughput > throughput_benchmark_results.txt
          gcc -o benchmark_overhead overhead_benchmark.c
          ./benchmark_overhead > overhead_benchmark_results.txt

      # Step 5: Save results
      - name: Save Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-benchmark-results
          path: |
            crypto_sign/falcon-512/clean/time_benchmark_results.txt
            crypto_sign/falcon-512/clean/cost_benchmark_results.txt
            crypto_sign/falcon-512/clean/throughput_benchmark_results.txt
            crypto_sign/falcon-512/clean/overhead_benchmark_results.txt
